### ISSUE TITLE
Kalender: Zyklische / Wiederkehrende Termine

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#424]
Zyklische / Wiederkehrende Termine
wöchentlich, monatlich, jährlich

https://www.ilch.de/forum-showposts-54053.html
https://www.ilch.de/forum-showposts-54816.html

FullCalendar 4.0.0-alpha.2 hat "Recurring events" als neue Funktion.
https://fullcalendar.io/docs/v4/release-notes

https://fullcalendar.io/docs/v4/recurring-events
https://fullcalendar.io/docs/v4/rrule-plugin

**Comment by hhunderter** [comment]
mittlerweile die Version 5.6.0 raus

**Comment by blackcoder87** [comment]
Nach Rücksprache mit hhunderter geschlossen.
