### ISSUE TITLE
Fehler im CKEditor BBCode-Plugin

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#445]
Bei folgenden Text steigt das BBCode-Plugin im CKEditor (den wir ja im Frontend benutzen) aus. Ein Beitrag im Forum lässt sich dann z.B. nicht bearbeiten.
Betrifft ebenfalls die Eingabe einer Signatur im User Panel.

`[[][/url]`

https://www.ilch.de/forum-showposts-54714.html
https://www.ilch.de/forum-showposts-54797.html
https://www.ilch.de/forum-showposts-56372.html

https://github.com/ckeditor/ckeditor-dev/issues/2782

**Comment by c0r1an** [comment]
Ich kann den Fehler leider nicht reproduzieren :/ bei mir wird es als <code> umgewandelt und ich kann das forum weiter bearbeiten. Hast du vielleicht noch mehr Schnipsel das ich es reproduzieren kann??

**Comment by blackcoder87** [comment]
Das ist kein Fehler in Ilch, sondern im BBCode-Plugin vom CKEditor. Siehe den Link zur Issue in deren Repo.
Deswegen ja auch die Idee im Frontend auch den HTML-Modus zu nutzen, aber mit einer anderen Konfiguration und mit HTMLPurifier zur Sicherheit.

Ich habe es gerade bei deren CKEditor-Demo getestet und der Fehler tritt noch auf.

**Comment by c0r1an** [comment]
Ja jetzt sehe ich es auch... die Buttons sind ausgegraut. Ich schau mir das noch mal an... kannst du eine Test-Seite aufsetzen wo wir das ohne BBCode testen können?

**Comment by blackcoder87** [comment]
Ich kann einen Branch anlegen und das vielleicht mal grob umsetzen für das Forum-Modul, aber wenn man das richtig umsetzen will, hängt da ja noch bisschen mehr dran. Siehe hier:
https://www.ilch.de/forum-showposts-56394.html

**Comment by c0r1an** [comment]
Ja das stimmt schon, aber irgendwo muss man ja Anfangen :) 
Also von mir aus, gerne auch eine Branch

**Comment by blackcoder87** [comment]
https://github.com/IlchCMS/Ilch-2.0/tree/feature/forum-ckeditor-html-frontend

- Behebt das Problem dieses Tickets (https://github.com/IlchCMS/Ilch-2.0/issues/445).
- Beinhaltet das Tabellen-Plugin und ermöglicht so Tabellen im Forum (https://github.com/IlchCMS/Ilch-2.0/issues/451)

Zu erledigen:
- "config_ilch_html_frontend" anpassen (ist bis jetzt quasi nur eine Kopie von "config_ilch_html")
- Bestehende Beiträge und Signaturen mit getHtmlFromBBCode() von BBCode zu HTML konvertieren (siehe TODO in config.php)
