### ISSUE TITLE
Menüpunkt "Seiten" fehlt, obwohl Nutzer die Rechte zum Bearbeiten von Seiten hat

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#450]
Menüpunkt "Seiten" fehlt, obwohl Nutzer die Rechte zum Bearbeiten von Seiten hat

> Der Reiter Seiten im Admincenter wird nur als Administrator angezeigt. Selbst wenn man bestimmten Gruppen die Berechtigung
> Seite bearbeitbar (Backend) gibt wird in der oberen Leiste der Reiter Seiten nicht angezeigt.

https://www.ilch.de/forum-showposts-54919.html

Siehe auch die angehängten Screenshots von SL_Evilfighter.

![01](https://user-images.githubusercontent.com/18415497/74098142-d8fb5300-4b14-11ea-9a89-77023662c108.jpg)

![02](https://user-images.githubusercontent.com/18415497/74098143-dac51680-4b14-11ea-8eb4-14de0d235750.jpg)

![03](https://user-images.githubusercontent.com/18415497/74098145-dc8eda00-4b14-11ea-8047-3882dd71abbf.jpg)

https://www.ilch.de/forum-showposts-55079.html

**Comment by c0r1an** [comment]
Ich habe mir das ganze jetzt angesehen... eine Auslagerung in ein eigenständiges Modul wäre die beste Lösung.
