### ISSUE TITLE
Benutzer-Modul: Kommentare auf Benutzerprofil

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#455]
https://www.ilch.de/index.php?forum-showposts-55104-p1#396900

> Hallo
> Ich wollte mal nachfragen ob es möglich wäre ein Gästebuch für die User im User Panel ein zu fügen so das sich die User untereinander Gästebucheinträge schicken können.
> 
> Ich frage daher das ich meine mal gelesen zu haben das dieses CMS nicht nur für Clans sondern auch als Community CMS gedacht war.

**Comment by blackcoder87** [comment]
Vielleicht könnte man als Alternative auch Kommentare auf der Profilseite eines Benutzers einbinden, welche optional deaktiviert/aktiviert werden können. Aktuell können Kommentare allerdings nur in einem einfachen Textfeld eingegeben werden. Hier möchte man dann vielleicht den CKEditor fürs Frontend nutzen.

- Mit Umsetzung auf Wechsel zu CKEditor 5 warten?

**Comment by hhunderter** [comment]
ich würde sagen warten
