### ISSUE TITLE
Benutzerdefinierte Weiterleitung nach Login

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#464]
> Beim betreten unserer Startseite erscheint bei uns die "ARTIKEL-Box". Ist so eingestellt und auch gewünscht :-)
> Jetzt möchte ich aber nach erfolgreichen Login sofort das FORUM haben !

https://www.ilch.de/forum-showposts-55817.html

https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/user/views/admin/settings/index.php
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/user/controllers/admin/Settings.php
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/user/controllers/Login.php#L84

**Comment by hhunderter** [comment]
Kann damit gelöst werden:

https://github.com/IlchCMS/Ilch-2.0/pull/524/commits/a359347b16484a047d9a9fa5bc18983ec5050811#diff-01a573b6748ca1a67ca3d94d6339608087d17b9dd611b84a70dc86729211f5baR178

**Comment by blackcoder87** [comment]
Looks like this is fixed?
