### ISSUE TITLE
Function ReflectionParameter::isArray() is deprecated

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#475]
Unit tests are failing with the message "Function ReflectionParameter::isArray() is deprecated" in Travis and PHP nightly (PHP 8.0.0-dev (cli) (built: May 13 2020 04:31:32) ( ZTS )).

> ReflectionParameter::isArray()
> ReflectionParameter::isCallable()
> ReflectionParameter::getClass()
>
> **These APIs have been superseded by ReflectionParameter::getType() since PHP 7.0**. Types introduced since that time are not available through the old APIs, and their behavior is getting increasingly confusing. This is how they interact with PHP 8 union types:
> 
> isArray() will return true if the type is array or ?array, but not any other union type
> Same for isCallable().
> getClass() will return a class for T|int etc, as long as the union only contains a single type. T1|T2 will return null.
> This behavior is not particularly reasonable or useful, and will get more confusing as new type system extensions are added.

https://github.com/IlchCMS/Ilch-2.0/issues/446

**Comment by blackcoder87** [comment]
Looks like this is triggered by the old version of PHPUnit or to be more precise "phpunit/phpunit-mock-objects".
We currently (as of today!) use version 6.5.14.

PHPUnit 7.5.20 requires PHP 7.1 or newer.
PHPUnit 8.5.8 requires PHP 7.2 or newer.
PHPUnit 9.2.5 requires PHP 7.3 or newer.

**PHP 8 is scheduled for Nov 26 2020.**
https://wiki.php.net/todo/php80#timetable

> This package is abandoned and no longer maintained. No replacement package was suggested.

https://github.com/sebastianbergmann/dbunit
https://packagist.org/packages/phpunit/dbunit
https://github.com/sebastianbergmann/dbunit/issues/217

https://github.com/sebastianbergmann/phpunit-mock-objects
https://packagist.org/packages/phpunit/phpunit-mock-objects

**Comment by blackcoder87** [comment]
With PHPUnit 7.5.20 on PHP 8
> Method ReflectionParameter::getClass() is deprecated

**Comment by sminnee** [comment]
FYI I've pushed a fork of phpunit-mock-objects for this reason https://github.com/sminnee/phpunit-mock-objects
