### ISSUE TITLE
Weiterleitung in Userliste

### ISSUE THREAD

**Issue by c0r1an** [IlchCMS/Ilch-2.0#509]
Weiterleitung zur Webseite fehlerhaft.

Wenn ohne HTTP oder HTTPS Angabe ist er Link fehlerhaft

index.php/user/index/index

**Comment by blackcoder87** [comment]
https://github.com/IlchCMS/Ilch-2.0/blob/v2.1.43/application/modules/user/views/index/index.php#L68
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/user/views/admin/profilefields/treat.php#L85

After adding a link addition in the admincenter for that field and the user entering https:// too
![image](https://user-images.githubusercontent.com/18415497/129468341-c29457ad-0d06-4f8e-a8c4-283b6b591715.png)

With no link addition and the user just entering www.google.de
![image](https://user-images.githubusercontent.com/18415497/129468389-eee90d92-e8ea-49b0-af40-7697164671a3.png)
