### ISSUE TITLE
Newsletter-Modul: Bestätigungsmail

### ISSUE THREAD

**Issue by hhunderter** [IlchCMS/Ilch-2.0#514]
Im Newsletter Modul eine Bestätigungsmail einpflegen

**Comment by blackcoder87** [comment]
Eine Bestätigungsmail könnte man auch als unnötig ansehen, weil es keinen großen Unterschied macht ob der Empfänger in der Bestätigungsmail auf "Möchte ich nicht" klickt oder im ersten Newsletter, den er erhalten könnte.

![unsubscribeFromNewsletter](https://user-images.githubusercontent.com/18415497/119215537-958ce400-bace-11eb-9b8f-51a7bd740869.png)

https://github.com/IlchCMS/Ilch-2.0/blob/v2.1.42/application/modules/newsletter/controllers/admin/Index.php#L156
https://github.com/IlchCMS/Ilch-2.0/blob/v2.1.42/application/modules/newsletter/layouts/mail/newsletter.php#L219

Ich bin dafür das Ticket zu schließen.

**Comment by hhunderter** [comment]
Es ging mal darum : 
1. als Gast kann man eine X-Beliebige E-Mail Adresse angeben.
2. muss glaube ich so was generell bestätigt werden dass man es wirklich haben will oder nicht?

**Comment by blackcoder87** [comment]
Das scheint der Unterschied zwischen Single Opt-in und Double Opt-in zu sein.

> Also, email compliance laws such as GDPR, CAN-SPAM, CASL don’t require a double opt-in subscription process.

Siehe auch:
https://www.termsfeed.com/blog/gdpr-email-newsletters/
