### ISSUE TITLE
Consider migrating to GitHub Actions or travis-ci.com

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#528]
**Describe the bug**

Travis is showing a warning regarding migrating to travis-ci.com for some time now. So either it should be looked into that or migrating to GitHub Actions. It is (at least to me) unclear how well Travis will be integrated into GitHub once they shut down travis-ci.org.

> Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com.

https://travis-ci.org/github/IlchCMS/Ilch-2.0

**Additional context**
https://docs.github.com/en/actions
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions
https://www.nymedia.no/en/blog/why-we-decided-migrate-from-travis-to-github-action
https://tomasvotruba.com/blog/2020/01/27/switch-travis-to-github-actions-to-reduce-stress/

**Comment by blackcoder87** [comment]
https://travis-ci.community/t/how-to-migrate-from-org-to-com-in-the-light-of-org-shutting-down/10566
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by blackcoder87** [comment]
Nicht vergessen. Wenn travis-ci.org morgen abgeschaltet wird, funktionieren wahrscheinlich die Unit Tests auf Travis nicht mehr und das Build-Skript wird auch nicht mehr angestoßen. Siehe die beiden Links oben um zu sehen wie man von travis-ci.org auf travis-ci.com wechselt.

![travis-ci-com](https://user-images.githubusercontent.com/18415497/121850859-ac99ad00-cced-11eb-809b-1ae28625654c.png)

**Comment by Mairu** [comment]
Hab im build script die Url zu travis-ci.com geändert und das build script "deployed".

https://github.com/IlchCMS/ilch2-build/commit/dbce2786c0ca59c00bc42467b89e651c4b243d22

Laut log Eintrag, scheint das script jetzt auch wieder erfolgreich getriggert zu werden.
