### ISSUE TITLE
multiple installation / same domain

### ISSUE THREAD

**Issue by raven3k** [IlchCMS/Ilch-2.0#537]
That is not possible, to install different ilch installation on a same domain.
e.g. mydomain.com/ilch2, mydomain.com/ilch3

I would loggedin on ilch2 and maybe on ilch3 on the same time, with different user IDs.

Maybe is a feature or a bug.

**Comment by blackcoder87** [comment]
Not sure if this can be considered a bug. I mean it is the same domain.
You could work with subdomains and then have multiple ilch installations with the same (different prefix) or a different database.

ilch2.mydomain.com
ilch3.mydomain.com

You would just need to configure your webserver to point to the correct directory (e.g. ilch2 or ilch3 directory depending on the subdomain) on your server.

**Comment by blackcoder87** [comment]
Guess this issue can be closed?
