### ISSUE TITLE
404 Version Check

### ISSUE THREAD

**Issue by well100** [IlchCMS/Ilch-2.0#568]
Versionsabfrage ist mit folgenden Fehler fehlgeschlagen: "The requested URL returned error: 404 ". Versuchen Sie den Updateserver zu wechseln, sollte dieses Problem nicht temporär sein.

**Comment by well100** [comment]
URL: https://ilch2.de/development/updateserver/stable/

**Comment by hhunderter** [comment]
Das Problem ist bekannt und wird auch dran gearbeitet.
