### ISSUE TITLE
Beta-Server blackcoder 

### ISSUE THREAD

**Issue by BlackRomeoIlch** [IlchCMS/Ilch-2.0#577]
Servus geht der Beta Server nicht mehr? 

bei mir kommt folgender Fehler. "Versionsabfrage ist mit folgenden Fehler fehlgeschlagen: "The requested URL returned error: 404 ". Versuchen Sie den Updateserver zu wechseln, sollte dieses Problem nicht temporär sein."

**Comment by c0r1an** [comment]
Bei mir funktioniert alles. Bitte schau noch mal.... vielleicht hast du dich vertippt.
