### ISSUE TITLE
Trigger build script with GitHub Actions

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#592]
**Is your feature request related to a problem? Please describe.**
The newest state of development version for users is out of date as the build script no longer runs with changes to the master.
Further it was comfortable to use the result of the build script for actual releases. The build script was trigger when creating a release/tag. This was previously done with Travis.

**Describe the solution you'd like**
Trigger the build script with GitHub Actions when the master changes and/or a release/tag is created. Try to replicate the behavior it had when Travis triggered it, please.

**Additional context**
https://github.com/IlchCMS/Ilch-2.0/blob/v2.1.43/.travis.yml#L28
https://github.com/IlchCMS/Ilch-2.0/tree/master/build

**Comment by Mairu** [comment]
I also have thought about that, but instead if just triggering the build script that was run on the ilch.de server, my plan is to completely move the logic into GitHub Actions to create the archive (and for tags also to create a release draft).

Have done something similar already (https://github.com/Mairu/nodist/blob/main/.github/workflows/release.yml).

**Comment by blackcoder87** [comment]
That sounds great as the build script issue is kind of a hurdle to a new release.

**Comment by Mairu** [comment]
Just as a note, we could potentially also trigger the update of all the update server files by GitHub actions. But I have not enough knowledge yet.
