### ISSUE TITLE
Migration von Bootstrap v3 nach Bootstrap v5

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#601]
**Describe the bug**
Inzwischen gibt es bereits Bootstrap v5.

> Migrating to v5
Track and review changes to the Bootstrap source files, documentation, and components to help you migrate from v4 to v5.

https://getbootstrap.com/docs/5.2/getting-started/introduction/
https://getbootstrap.com/docs/5.2/migration/
https://getbootstrap.com/docs/5.0/migration/

**Additional context**
[Migration von Bootstrap v3 nach Bootstrap v4](https://github.com/IlchCMS/Ilch-2.0/issues/435)

**Comment by Slipi85** [comment]
**Bereits bearbeitet**

1. Standard Layout
2. Admincenter Frond
3. --- Menue
4. --- Layouts
5. --- Boxen
6. --- Seiten

**Comment by blackcoder87** [comment]
### Prepare modules and layouts for bootstrap 5
**Remaining modules that need updating**
- [ ] admin
- [ ] article
- [ ] awards
- [ ] away
- [ ] bbcodeconvert
- [ ] birthday
- [ ] calendar
- [ ] checkoutbasic
- [ ] checkout
- [ ] comment
- [ ] contact
- [ ] cookieconsent
- [ ] downloads
- [ ] error
- [ ] events
- [ ] faq
- [ ] forum
- [ ] gallery
- [ ] guestbook
- [ ] history
- [ ] imprint
- [ ] install
- [ ] jobs
- [ ] link
- [ ] linkus
- [ ] media
- [ ] newsletter
- [ ] partner
- [ ] privacy
- [ ] rule
- [ ] sample
- [ ] shop
- [ ] shoutbox
- [ ] statistic
- [ ] teams
- [ ] training
- [ ] user
- [ ] vote
- [ ] war

**External modules** 
- [ ] kvticket
- [ ] membermap
- [ ] radiohoerercharts
- [ ] steamauth
- [ ] socialbar
- [ ] wgquicklogin
- ?

**Remaining layouts that need updating**
- [ ] clan3columns
- [ ] ilchlayout
- [ ] privatlayout
- [ ] ilch_comm
- [ ] esportlayout
- [ ] ilch_wot

**Comment by blackcoder87** [comment]
https://github.com/IlchCMS/Ilch-2.0/pull/970
