### ISSUE TITLE
Artikel-Modul: Weiterlesen Funktion

### ISSUE THREAD

**Issue by opticmed1a** [IlchCMS/Ilch-2.0#613]
Hallo,
wie ist es möglich bei einem Post die "Weiterlesen" Funktion einzubinden so wie auf eurer Startseite??
Danke

**Comment by blackcoder87** [comment]
Das sollte bereits möglich sein. Ist dies hier die Funktion, die Sie suchen?

![article-preview](https://user-images.githubusercontent.com/18415497/209438517-0178227b-a78f-473e-814c-cab54efd613c.png)

![article-previewstop-admincenter](https://user-images.githubusercontent.com/18415497/209438519-e5d6035d-2ad6-49d9-a6dd-607399f21261.png)

**Comment by blackcoder87** [comment]
Danke und ebenfalls frohe Weihnachten.
