### ISSUE TITLE
User-Modul: Benutzerdefinierte Pflichtfelder 

### ISSUE THREAD

**Issue by hhunderter** [IlchCMS/Ilch-2.0#619]
Bei der Registrierung weitere Felder anzeigen lassen
z.b. Feld für eine Kundennummer

**Comment by blackcoder87** [comment]
> [...] kann man bei dem Registrierungsfeld ein Zusatz Feld einbauen was aber nur bei der Registrierung wichtig ist [...]

https://www.ilch.de/forum-showposts-58750.html
