### ISSUE TITLE
Modul Auszeichnungen: Auszeichnugen im Kalender anzeigen

### ISSUE THREAD

**Issue by ghost** [IlchCMS/Ilch-2.0#782]
Module Funktioniert :+1: 

Da jedoch die Eingabe eines Datums verpflichtend ist, könnte man dies vielleicht auch zukünftig im **Kalender** anzeigen !?

**Comment by hhunderter** [comment]
Wie der Titel schon sagt ist eine Auszeichnung die einer an einem bestimmten Tag erhalten hatte. Meist liegt ja der Termin in der Vergangenheit und ist einmalig da macht ein Eintrag glaube ich weniger Sinn oder? Könnt mich gerne vom Gegenteil überzeugen;)

**Comment by RTX2070** [comment]
Naja...Auszeichnungen können auch in der Zukunft vergeben werden. Denke da gerade so an Bundeswehr...da gibt es auch Beförderungen zu bestimmten Zeitpunkten.
Oder z.B. User XYZ ist am 31.12.2023 10 Jahre Teil der Community und wird an diesem Tag ausgezeichnet für seine treuen Dienste etc. 
Nur so als Idee :)

**Comment by blackcoder87** [comment]
Das Beispiel klingt für mich relativ weit hergeholt.
Ob man im Kalender stehen haben muss, dass an dem Tag jemand eine Auszeichnung erhalten hat, weiß ich nicht.
Hat die Funktion schon einmal jemand angefragt?

**Comment by RTX2070** [comment]
Nö.. keine Anfrage. War nur sone Idee als ich mir das Module angesehen habe
