### ISSUE TITLE
Login bevor man auf die Seite kommt

### ISSUE THREAD

**Issue by Stormez1998** [IlchCMS/Ilch-2.0#811]
Hay Hay,

ich muss mich mit einer etwas Peinlichen Bitte an euch wenden...

Ich habe vorhin aktiviert das man sich bevor man auf die Seite kommt einlogen muss, siehe Bild.

![image](https://github.com/IlchCMS/Ilch-2.0/assets/57358176/ed472603-8bd9-41b5-889f-4e48948c1cee)

Ich bin nun mit meinen Anpassungen so weit fertig und würde dies gerne wieder deaktivieren. Ich habe leider vergessen wo ich das aktiviert habe. Wäre super wenn mir das nochmal jemand sagen könnte, woch ich die Option zum Aktivieren und deaktivieren finde :D 

Danke

**Comment by LordSchirmer** [comment]
Du meinst die Option "Wartungsarbeiten"?

Backend (Adminbereich) > Settings (oben rechts Zahnräder) > Wartungsarbeiten

www.domain.de/index.php/admin/admin/settings/maintenance

**Comment by Stormez1998** [comment]
Ne Wartungsarbeiten ist was anderes. Das kenne ich, dass habe ich auch gefunden, dort lässt sich aber eben nur der Wartungsmodus einschalten hier wird aber eben ein Passwort abgefragt, ich weiss auch das ich es im Backend eingestellt hatte, aber ich finds halt nicht mehr :D

**Comment by Stormez1998** [comment]
Vergesst was ich gesagt habe. Ich bin Mega Dumm. Ich hatte es nicht im Ilch aktiviert sonder in meinem Cloudpanel. Ich sollte mal schlafen, damit so was nicht nochmal passiert. Danke für die Hilfe ! Und sorry für die Verwirrung! :)
