### ISSUE TITLE
Error beim öffnen der Nachrichten Seite

### ISSUE THREAD

**Issue by Stormez1998** [IlchCMS/Ilch-2.0#813]
**Describe the bug**
Wenn ich versuch über UserPanel -> Nachrichten (dialog) bekomme ich eine Fehler Meldung angezeigt

**To Reproduce**
1. Go to 'userPanel'
2. Click on 'nachrichten'
3. See error

**Expected behavior**
Gestern Abend hatte das Senden von Nachrichten noch Ohne probleme funktioniert, nun erhalte ich eine Fehlermeldung

`Fatal error: Uncaught TypeError: Modules\User\Models\Dialog::setId(): Argument #1 ($id) must be of type int, null given, called in /home/mole/htdocs/mole.tz-gaming.com/application/modules/user/mappers/Dialog.php on line 51 and defined in /home/mole/htdocs/mole.tz-gaming.com/application/modules/user/models/Dialog.php:97 Stack trace: #0 /home/mole/htdocs/mole.tz-gaming.com/application/modules/user/mappers/Dialog.php(51): Modules\User\Models\Dialog->setId() #1 /home/mole/htdocs/mole.tz-gaming.com/application/modules/user/controllers/Panel.php(465): Modules\User\Mappers\Dialog->getDialog() #2 /home/mole/htdocs/mole.tz-gaming.com/application/libraries/Ilch/Page.php(241): Modules\User\Controllers\Panel->dialogAction() #3 /home/mole/htdocs/mole.tz-gaming.com/application/libraries/Ilch/Page.php(135): Ilch\Page->loadController() #4 /home/mole/htdocs/mole.tz-gaming.com/index.php(67): Ilch\Page->loadPage() #5 {main} thrown in /home/mole/htdocs/mole.tz-gaming.com/application/modules/user/models/Dialog.php on line 97`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Webserver Ngnix, PHP Version 8.0 (ich habe auch 7.4 probiert, ohne Erfolg)

**Comment by blackcoder87** [comment]
Moin,

kann den Fehler nachvollziehen, wenn einer der anderen Benutzer gelöscht wurde.
