### ISSUE TITLE
Navi/Box für Forum fehlerhaft

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#832]
**Describe the bug**
Ich hab Heute mein CMS geupdated und folgenden fehler erhalten. Siehe screenshot.

**To Reproduce**
Erstelle irgendwo in der Navi eine Box mit Forum.
Lass diese Navi/Box auf der Seite anzeigen.

**Expected behavior**
Das keine Fehler erscheinen.

**Screenshots**
https://prnt.sc/XkP7rCc9m5su

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 2.1.53

Äeaä
Irgendwie gehen die Boxen bei Microsoft Edge.

**Comment by TheFrozenThr0ne** [comment]
Ok Sorry kann wieder geschlossen werden. War nur irgendwas mit einem Cookie. Habe diese bereinigt und jetzt funktioniert es wieder. Danke sehr drotzdem. 😊

**Comment by TheFrozenThr0ne** [comment]
Also doch nicht, wenn man eingeloggt ist erscheint der fehler. Nicht so bei Gästen.

Hab folgende Box an der Seite:
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/a0662ccd-68c2-4d12-b99b-527ebf0911fa)

**Comment by hhunderter** [comment]
Die Seite mit den Fehlermeldungen kann leider nicht richtig angezeigt werden (abgeschnitten).
Welche Version des Forum-Moduls ist bei dir in Benutzung?

**Comment by TheFrozenThr0ne** [comment]
Die Version Forum Modul 1.34.1.

**Comment by hhunderter** [comment]
Jetzt ist der Fehler verständlich ;) Du musst in deinem Layout die Datei "./application/layouts/gc/views/modules/forum/boxes/views/forum.php" Updaten.
Bei deiner Version wäre es diese hier: https://github.com/IlchCMS/Ilch-2.0/blob/459ba4b39dfc313cd1457cbccda9aa926601dbd6/application/modules/forum/boxes/views/forum.php

**Comment by TheFrozenThr0ne** [comment]
Alles klar danke sehr hat geklappt.
