### ISSUE TITLE
Gallery - Kategorien Menu buggt

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#853]
**Describe the bug**
In der Gallery das Menu is buggy.

**To Reproduce**
Menu haben
Gallery Link erstellen
Gehe zur Gallery und drücke bei Kategorien auf Alle
Wie im screen zu sehen tut das cms die menu namen umbenennen

**Expected behavior**
Das es ohne bugs funktioniert also keine umbenennung statt findet.

**Screenshots**
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/47a8978a-3e4f-4317-93c2-4b96bc96ad48)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 2.1.54
 - Gallery Modul 1.22.1

**Comment by blackcoder87** [comment]
Hier brauchen wir vermutlich noch mehr Informationen zu dem Menü oben in deinem Screenshot. Wie hast du das angelegt bzw. welches Layout benutzt du?

Ich gehe mal davon aus, dass du dort verschiedene Galerien verlinkt hast und bei der Auswahl von "All Categories" dort überall dann auch "All Categories" steht?

**Comment by TheFrozenThr0ne** [comment]
Soweit ich mich recht erinnere ist das dass [Ilch-Layout](https://github.com/Slipi85/ilchlayout).

Ich hab einfach nur auf die Kategorie durch geklickt und nachn ersten klick hat sich das Menu verändert. Ohne ersichtlichen Grund.


Das is das Menu 3 - Backend Ansicht
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/9d9c12bc-f324-4ebe-bc33-23628056f582)

**Comment by TheFrozenThr0ne** [comment]
Ist doch kein Fehler vom CMS. War ein Fehler von mir. Hatte da eine Falsche class drinnen.
