### ISSUE TITLE
Forum: Fehler beim aufrufen Frontend

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#857]
**Describe the bug**
```
An unexpected error occurred:
MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY `p`.`topic_id` ORDER BY `p`.`date_created` DESC' at line 1
in Query: SELECT `p`.`id`,`p`.`topic_id`,MAX(p.date_created) AS `date_created`,`p`.`user_id`,`p`.`forum_id`,`tr`.`datetime` AS `topic_read`,`fr`.`datetime` AS `forum_read` FROM `ilch_forum_posts` AS `p` LEFT JOIN `ilch_forum_topics_read` AS `tr` ON (`tr`.`user_id` = "1" AND `tr`.`topic_id` = `p`.`topic_id` AND `tr`.`datetime` >= `p`.`date_created`) LEFT JOIN `ilch_forum_read` AS `fr` ON (`fr`.`user_id` = "1" AND `fr`.`forum_id` = `p`.`forum_id` AND `fr`.`datetime` >= `p`.`date_created`) WHERE `p`.`topic_id` IN () GROUP BY `p`.`topic_id` ORDER BY `p`.`date_created` DESC
```

Also ich hab eine Neue Kategorie erstellt und die dazugehörigen Forums. Und dann wollte ich drauf gehen und dann erschien der fehler. Dort wo bereits einträge vorhanden sind lassen sich problemlos aufrufen.

**To Reproduce**
Erstelle eine Forum Kategorie
Erstelle Unter Foren und setze die Rechte
Versuche im Frontend darauf zuzugreifen

**Expected behavior**
Das man das Forum ohne Fehler aufrufen kann.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 2.1.54
 - Forum Modul Version 1.34.2

**Additional context**
Wohl möglich das dieser schon bei euch gesehen wurde wenn nicht dann hat es sich ja gelohnt zu melden.

**Comment by blackcoder87** [comment]
Moin,

bitte einmal die neueste Version (1.34.3) vom Forum testen.

Gruß
blackcoder

**Comment by TheFrozenThr0ne** [comment]
Alles klar danke für den Hinweis. Es funktioniert wieder. Danke sehr. 😉
