### ISSUE TITLE
sliptree/bootstrap-tokenfield is deprecated

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#886]
**Describe the bug**
sliptree/bootstrap-tokenfield is deprecated and has an jQuery dependency.

> This repository has been archived by the owner on Sep 28, 2020. It is now read-only. 

> This project is no longer maintained!

Alternative without jQuery:
https://github.com/KaneCohen/tokenfield

**Additional context**
https://github.com/sliptree/bootstrap-tokenfield
https://github.com/KaneCohen/tokenfield

**Comment by blackcoder87** [comment]
Not compatible with Bootstrap 5?
https://www.ilch.de/forum-showposts-58597-p5.html#408090
https://www.ilch.de/forum-showposts-58597-p5.html#408094

**Comment by hhunderter** [comment]
Wäre das hier vlt eine alternative ? : https://github.com/Choices-js/Choices
auch für Chosen?

**Comment by blackcoder87** [comment]
Müsste man mal für beides testen, Auch ob man es vom Aussehen her an den aktuellen Stand anpassen kann (oder es wenigstens zu Bootstrap 5 passt). Wenn das klappt, dann könnte man in einem Branch alle Stellen auf "Choices" umstellen.

chosen und tokenfield nutzen wir relativ oft in Ilch. Hier hatte ich mir einen groben Überblick verschafft:
https://www.ilch.de/forum-showposts-58657.html#408034

In der Issue für Chosen hatte ich "Choices" sogar schon verlinkt:
https://github.com/IlchCMS/Ilch-2.0/issues/719

Hatte mich damit aber noch nicht genauer beschäftigt. Ist aber gut, dass es anscheinend ein aktives Projekt ist.

**Comment by hhunderter** [comment]
Das dachte ich mir auch und sah vielversprechend aus ;) werde mich mal daran setzen
