### ISSUE TITLE
Locale switch: DE - Fehler bei den Boxen

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#891]
**Describe the bug**
Ich habe mein CMS per Frontend auf DE geschaltet und diesen Fehler, am Rand wo die Boxen sind, erhalten.

```
Fatal error: Uncaught Error: Call to a member function getContent() on null in /application/libraries/Ilch/Layout/Helper/Menu/Model.php:161
Stack trace:
#0 /application/libraries/Ilch/Layout/Helper/GetMenu.php(62): Ilch\Layout\Helper\Menu\Model->getItems()
#1 [internal function]: Ilch\Layout\Helper\GetMenu->getMenu()
#2 /application/libraries/Ilch/Layout/Base.php(45): call_user_func_array()
#3 /application/layouts/gc/index.php(21): Ilch\Layout\Base->__call()
#4 /application/libraries/Ilch/Layout/Base.php(129): include('...')
#5 /application/libraries/Ilch/Page.php(186): Ilch\Layout\Base->loadScript()
#6 /index.php(68): Ilch\Page->loadPage()
#7 {main}
  thrown in /application/libraries/Ilch/Layout/Helper/Menu/Model.php on line 161
```

**To Reproduce**
Auf Deutsch schalten.
Fehlercode erscheint.

**Screenshots**
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/04b201c0-8ab9-4c1c-aa97-88b61159dfee)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 2.1.56

**Comment by blackcoder87** [comment]
Kann das Problem nachvollziehen.

1. Eigene Box erstellen.
2. Box zum Menü hinzufügen
3. "Mehrsprachige Einstellungen" aktivieren.

Für die Box fehlt eine "Locale".

Siehe auch den ähnlichen Fehler mit Seiten:
Mehrsprachige Seiten #630

**Comment by blackcoder87** [comment]
Moin,

kannst du das Problem mit dieser Änderung noch nachvollziehen?
