### ISSUE TITLE
Erweiterte-Layout-Einstellungen-(settings-Array) - fehler beim aufrufen von getLayoutSetting

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#898]
**Describe the bug**
Es geht um folgenden link:
https://github.com/IlchCMS/Ilch-2.0/wiki/Erweiterte-Layout-Einstellungen-(settings-Array)

Ich kopiere die Settings in meine Config, und rufe anschließend get Layout Setting auf und erhalte folgenden fehler.

`Fatal error: Uncaught Error: Call to undefined method Ilch\View::getLayoutSetting() in /mnt/web202/a3/31/54502131/htdocs/application/modules/user/views/regist/input.php:44 Stack trace: #0 /mnt/web202/a3/31/54502131/htdocs/application/libraries/Ilch/View.php(22): include() #1 /mnt/web202/a3/31/54502131/htdocs/application/libraries/Ilch/Page.php(159): Ilch\View->loadScript() #2 /mnt/web202/a3/31/54502131/htdocs/index.php(68): Ilch\Page->loadPage() #3 {main} thrown in /mnt/web202/a3/31/54502131/htdocs/application/modules/user/views/regist/input.php on line 44`

**To Reproduce**
Entsprechend kopieren und dann versuchen aufzurufen:
https://github.com/IlchCMS/Ilch-2.0/wiki/Erweiterte-Layout-Einstellungen-(settings-Array)

**Screenshots**
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/0875454e-7244-42b6-bb34-d4c84703336d)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 2.1.56

**Additional context**
<?php echo $this->getLayoutSetting('title'); ?>

**Comment by blackcoder87** [comment]
In welche config.php wurde das eingefügt? Bei der von dir verlinkten Dokumentation geht es darum, wie man als Entwickler/Designer eines Layouts "erweiterte Layout-Einstellungen" nutzen kann. Wenn dies im Layout genutzt wird, werden im Admincenter für den Benutzer die entsprechenden Einstellungen angezeigt. Arbeitest du gerade an einem Layout?

Ich habe gerade testweise das "Ilch-Privat"-Layout installiert, welches dies nutzt und konnte dann eine Einstellung für das Layout ändern und die Änderung auch auf der Seite sehen.

**Comment by TheFrozenThr0ne** [comment]
Ich benutz das layout. Kann die settings im admin bereich sehen.
aber wenn ich dann echo getLayoutSetting('title'); kommt der fehler bei mir. Oder mache ich das was falsch?

**Comment by TheFrozenThr0ne** [comment]
Oh okay ich glaube dann hab ich das glaub missverstanden. Hatte versucht das in ein anderes modul anzuwenden. Drotzdem danke.
