### ISSUE TITLE
Events: Column for details too narrow

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#909]
**Describe the bug**
In the event view the column for the event details can be too narrow, because the details and comments are displayed next to each other.
See the screenshot below.

View that needs to be changed to fix this:
https://github.com/IlchCMS/Ilch-2.0/blob/master/application/modules/events/views/show/event.php

Might be better to display the comments below the event details and therefore have the full width available in the layout to display the details.

**Screenshots**
![grafik](https://github.com/IlchCMS/Ilch-2.0/assets/18415497/2ad3214c-bff8-49e2-8839-57e627e88ea2)

**Additional context**
https://www.ilch.de/forum-showposts-58665.html

**Comment by blackcoder87** [comment]
@hhunderter 
Was ist deine Meinung hierzu? Kommentare unterhalb der Details anzeigen oder so lassen wie bisher?

**Comment by hhunderter** [comment]
Also, darunter hätte schon mehr Voreile als Nachteile.
Schon allein das einige Texte in mehreren Zeilen wandern.

**Comment by Slipi85** [comment]
Ich würde es unterhalb ausgeben lassen, eventuell mit einem Border von 1px damit es stylisch besser aussieht.
