### ISSUE TITLE
Reply im Forum fehler durch prefix

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [IlchCMS/Ilch-2.0#922]
**Describe the bug**
Im Forum taucht folgender Fehler auf. Unzwar hat das Topic ein prefix gesetzt.

**To Reproduce**
1. Forum Erstellen mit prefix
2. Topic erstellen mit prefix
3. Auf Topic antworten

**Screenshots**
![image](https://github.com/IlchCMS/Ilch-2.0/assets/11060723/18bc1fdf-4314-426c-972d-df3ec673cf5d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 2.1.57
 - Forum Version: 1.34.5

**Comment by blackcoder87** [comment]
Kann das Problem nachvollziehen und schaue es mir gerade genauer an.
