### ISSUE TITLE
Update designer documentation for Bootstrap 5

### ISSUE THREAD

**Issue by blackcoder87** [IlchCMS/Ilch-2.0#982]
The following documentation needs to be updated for Bootstrap 5. They are still referring to classes, components and more of Bootstrap 3.4.

https://github.com/IlchCMS/Ilch-2.0/wiki/Doku-Designer-Dynamische-Men%C3%BCs
https://github.com/IlchCMS/Ilch-2.0/wiki/Doku-Designer-Top-Navigation
https://github.com/IlchCMS/Ilch-2.0/wiki/Views-%C3%BCberschreiben

**Documentation for Bootstrap 5.3**
https://getbootstrap.com/docs/5.3/getting-started/introduction/

**Comment by LordSchirmer** [comment]
I have revised these 3 Wiki entries.

**Comment by blackcoder87** [comment]
Thanks.
